import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./_components/sidebar";
import { Header } from "./_components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoginPage = false;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-neutral-50 `}
      >
        <Sidebar />
        <div
          className={`min-h-screen flex-1 flex flex-col transition-all duration-300 ${
            !isLoginPage ? "lg:pl-72" : ""
          }`}
        >
          <Header />
          <main className="p-4 md:p-6 flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
